# Generated by Django 4.0.8 on 2023-01-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='custom_user',
            new_name='user',
        ),
    ]
