# Generated by Django 4.1.3 on 2022-12-17 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
