# Generated by Django 4.0.8 on 2023-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='static/images/img1.png', help_text='uplaod a product image', upload_to='static/images/', verbose_name='Image'),
        ),
    ]
