# Generated by Django 4.0.8 on 2023-01-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_is_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_feature',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='featured_image', to='products.productimage'),
        ),
    ]
