# Generated by Django 4.0.8 on 2023-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productimage_is_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add a alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(default='products/images/img1.png', help_text='uplaod a featured image', upload_to='products/images/', verbose_name='Image'),
        ),
    ]
